
package Logic;


public class TextKeeper {
    
    public String defaultKeysDistribution() {
        return "q=rr3;\n"
                + "w=kks;\n"
                + "e=ppz;\n"
                + "r=000;\n"
                + "t=lxm;\n"
                + "y=nam;\n"
                + "u=lod;\n"
                + "i=019;\n"
                + "o=mzn;\n"
                + "p=www;\n"
                + "a=xcd;\n"
                + "s=pq3;\n"
                + "d=mld;\n"
                + "f=lao;\n"
                + "h=com;\n"
                + "j=ink;\n"
                + "k=pop;\n"
                + "l=awq;\n"
                + "ñ=luk;\n"
                + "z=pen;\n"
                + "x=bty;\n"
                + "c=vag;\n"
                + "v=ope;\n"
                + "b=min;\n"
                + "n=sec;\n"
                + "m=tur;\n"
                + "g=kew;\n"
                + " = ;\n"
                + "Q=lld;\n"
                + "W=910;\n"
                + "E=plz;\n"
                + "R=999;\n"
                + "T=mnd;\n"
                + "Y=num;\n"
                + "U=dol;\n"
                + "I=091;\n"
                + "O=hjs;\n"
                + "P=ttt;\n"
                + "A=opq;\n"
                + "S=3mk;\n"
                + "D=63a;\n"
                + "F=kun;\n"
                + "H=org;\n"
                + "J=ske;\n"
                + "K=ice;\n"
                + "L=xmA;\n"
                + "Ñ=l31;\n"
                + "Z=la0;\n"
                + "X=no1;\n"
                + "C=p20;\n"
                + "V=an7;\n"
                + "B=m1n;\n"
                + "N=vq8;\n"
                + "M=lz0;\n"
                + "G=tDs;\n"
                + "á=012;\n"
                + "é=893;\n"
                + "í=kl3;\n"
                + "ó=xk4;\n"
                + "ú=sSw;\n"
                + "Á=j07;\n"
                + "É=c36;\n"
                + "Í=m34;\n"
                + "Ó=Mk0;\n"
                + "Ú=BfR;\n"
                + "0=mmW;\n"
                + "1=mnX;\n"
                + "2=XsW;\n"
                + "3=004;\n"
                + "4=maq;\n"
                + "5=mzu;\n"
                + "6=HgR;\n"
                + "7=lkE;\n"
                + "8=cXS;\n"
                + "9=eMS;\n"
                + "/=1d1;\n"
                + "$=mlW;\n"
                + ",=mQs;\n"
                + "\"=mZZ;\n"/*quote*/
                + ".=JT2;\n"/*dot*/
                + ":=92g;\n"/*dot*/
                + "#=kma;";
    }
    
    public String randomKeysBuildUp() {
        return "q="+Static.run.generateID()+";\n"
                + "w="+Static.run.generateID()+";\n"
                + "e="+Static.run.generateID()+";\n"
                + "r="+Static.run.generateID()+";\n"
                + "t="+Static.run.generateID()+";\n"
                + "y="+Static.run.generateID()+";\n"
                + "u="+Static.run.generateID()+";\n"
                + "i="+Static.run.generateID()+";\n"
                + "o="+Static.run.generateID()+";\n"
                + "p="+Static.run.generateID()+";\n"
                + "a="+Static.run.generateID()+";\n"
                + "s="+Static.run.generateID()+";\n"
                + "d="+Static.run.generateID()+";\n"
                + "f="+Static.run.generateID()+";\n"
                + "h="+Static.run.generateID()+";\n"
                + "j="+Static.run.generateID()+";\n"
                + "k="+Static.run.generateID()+";\n"
                + "l="+Static.run.generateID()+";\n"
                + "ñ="+Static.run.generateID()+";\n"
                + "z="+Static.run.generateID()+";\n"
                + "x="+Static.run.generateID()+";\n"
                + "c="+Static.run.generateID()+";\n"
                + "v="+Static.run.generateID()+";\n"
                + "b="+Static.run.generateID()+";\n"
                + "n="+Static.run.generateID()+";\n"
                + "m="+Static.run.generateID()+";\n"
                + "g="+Static.run.generateID()+";\n"
                + " ="+Static.run.generateID()+";\n"
                + "Q="+Static.run.generateID()+";\n"
                + "W="+Static.run.generateID()+";\n"
                + "E="+Static.run.generateID()+";\n"
                + "R="+Static.run.generateID()+";\n"
                + "T="+Static.run.generateID()+";\n"
                + "Y="+Static.run.generateID()+";\n"
                + "U="+Static.run.generateID()+";\n"
                + "I="+Static.run.generateID()+";\n"
                + "O="+Static.run.generateID()+";\n"
                + "P="+Static.run.generateID()+";\n"
                + "A="+Static.run.generateID()+";\n"
                + "S="+Static.run.generateID()+";\n"
                + "D="+Static.run.generateID()+";\n"
                + "F="+Static.run.generateID()+";\n"
                + "H="+Static.run.generateID()+";\n"
                + "J="+Static.run.generateID()+";\n"
                + "K="+Static.run.generateID()+";\n"
                + "L="+Static.run.generateID()+";\n"
                + "Ñ="+Static.run.generateID()+";\n"
                + "Z="+Static.run.generateID()+";\n"
                + "X="+Static.run.generateID()+";\n"
                + "C="+Static.run.generateID()+";\n"
                + "V="+Static.run.generateID()+";\n"
                + "B="+Static.run.generateID()+";\n"
                + "N="+Static.run.generateID()+";\n"
                + "M="+Static.run.generateID()+";\n"
                + "G="+Static.run.generateID()+";\n"
                + "á="+Static.run.generateID()+";\n"
                + "é="+Static.run.generateID()+";\n"
                + "í="+Static.run.generateID()+";\n"
                + "ó="+Static.run.generateID()+";\n"
                + "ú="+Static.run.generateID()+";\n"
                + "Á="+Static.run.generateID()+";\n"
                + "É="+Static.run.generateID()+";\n"
                + "Í="+Static.run.generateID()+";\n"
                + "Ó="+Static.run.generateID()+";\n"
                + "Ú="+Static.run.generateID()+";\n"
                + "0="+Static.run.generateID()+";\n"
                + "1="+Static.run.generateID()+";\n"
                + "2="+Static.run.generateID()+";\n"
                + "3="+Static.run.generateID()+";\n"
                + "4="+Static.run.generateID()+";\n"
                + "5="+Static.run.generateID()+";\n"
                + "6="+Static.run.generateID()+";\n"
                + "7="+Static.run.generateID()+";\n"
                + "8="+Static.run.generateID()+";\n"
                + "9="+Static.run.generateID()+";\n"
                + "/="+Static.run.generateID()+";\n"
                + "$="+Static.run.generateID()+";\n"
                + ",="+Static.run.generateID()+";\n"
                + "\"="+Static.run.generateID()+";\n"/*quote*/
                + ".="+Static.run.generateID()+";\n"/*dot*/
                + ":="+Static.run.generateID()+";\n"/*dot*/
                + "#="+Static.run.generateID()+";\n";
    }
    
    public String USERMANUALTEXT() {
        return Static.title + ". Version " + Static.version + "\n"
                + "\n"
                + "User manual.\n"
                + "1- How to create your own encrypted patron.\n"
                + "2- Separator Char.\n"
                + "3- About the author.\n"
                + "\n"
                + "------------------------------------O------------------------------------\n"
                + "\n"
                + "1 - HOW TO CREATE YOUR OWN ENCRYPTED PATRON.\n"
                + "\n"
                + "Please read all the following lines before making your own file.\n"
                + "\n"
                + "Open the Data Folder either clicking the button \"Data Folder\" or \n"
                + "going by your on. Path: " + Static.DataFolderPath + "\n"
                + "Look for a .txt file called \"characters\".\n"
                + "MAKE A COPY OF IT AND START WORKING IN THAT FILE. Everytime\n"
                + "you start the program the \"characters.txt\" file is created again\n"
                + "because of program malfunction control. If you make changes on\n"
                + "\"characters.txt\" all will be deleted next time you run the program.\n"
                + "Rename the copy of \"characters.txt\" to, for example, \"chars2.txt\";\n"
                + "you can name it with any name you want.\n"
                + "\n"
                + "Inside the file you will find all the letters of the alphabet 2 times\n"
                + "(uppercase and lowercase), some vowels with accent mark and symbols.\n"
                + "Just next of any letter/simbol you'll see an \"=\" and next to it the\n"
                + "encrypted equivalent of the letter before seen. Example:\n"
                + "\n"
                + "a=xcd;\n"
                + "\n"
                + "Syntax: LETTER=ENCRYPTEDEQUIVALENT;\n"
                + "\n"
                + "To change the encryption of the, for example, letter \"a\"\n"
                + "you only have to change the encrypted text contained between the\n"
                + "\"=\" and the \";\" with any other text that you want. Example:\n"
                + "\n"
                + "a=ExampleText;\n"
                + "\n"
                + "So, keeping in mind that \"p=www;\", \"l=awq;\", \"e=ppz;\" and the\n"
                + "Separator Char is \"°\", you will get from the word \"apple\" the\n"
                + "encryption of \"ExampleText°www°www°awq°ppz°\". Change all the \n"
                + "encrypted equivalents that you want with no length limitation.\n"
                + "\n"
                + "To load the file \"chars2.txt\":\n"
                + "1-Make sure that the chars file is inside the Data folder.\n"
                + "2-Run the program.\n"
                + "3-Go to options and seek for \"Custom Char file\".\n"
                + "4-Type the name of the edited chars file (without \".txt\") and click\n"
                + "on \"Load and save\".\n"
                + "5-You will see a \"Success!\" popup message (if it's enabled) indicating\n"
                + "that \"chars2.txt\" has been successfully loaded, saved and settled as \n"
                + "default. You will see as well the program indicating that \"chars2\" is\n"
                + "the current file of characters.\n"
                + "\n"
                + "If there is something wrong syntax inside your file, the program \n"
                + "will crash, close, and will set the default characters next time \n"
                + "you start the program.\n"
                + "\n"
                + "If the file is not at the correct path or you have mistaken the name \n"
                + "of the file, there will appear a error message.\n"
                + "\n"
                + "RULES OF THE CHARACTERS FILE, not following the next rules will result\n"
                + "in program malfunction:\n"
                + "\n"
                + "- DO NOT CHANGE THE SYNTAX OF \"letter=encrypt;\". If there is a missing\n"
                + "\"=\", \";\", letter or encrypted equivalent it will result in a program crash.\n"
                + "\n"
                + "- Do not leave a space between two different syntaxes settings. Example:\n"
                + "\"a=abc; b=cvb;c=kei;\". It must be like: \"a=abc;b=cvd;c=kei;\". \n"
                + "Not doing so will result in a program crash.\n"
                + "\n"
                + "- Do not leave a space at the beginning or at the end of the txt file.\n"
                + "There shouldn't be any space. If it is so, it will result in a program crash.\n"
                + "\n"
                + "-After reading the previus rule, you may wonder of a syntax letter that appears as\n"
                + "\" = ;\". That's the syntax to encrypt the space (\" \"). You can encrypt the space,\n"
                + "though. Example: \" =spaceExample;\".\n"
                + "\n"
                + "Take in consideration: \n"
                + "\n"
                + "1-YOU CAN ADD EVEN MORE CHARS. If there is a letter/simbol that does not exist inside\n"
                + "the file like \"&\". The program will \"encrypt\" it as \"&\". If you want to encrypt that\n"
                + "letter just follow the syntax of \"letter=EncryptedEquivalent;\" and add it at the\n"
                + "beginning/middle/end of your custom file. For example, inside the default txt \n"
                + "characters you may find: \"q=rr3;w=kks;e=ppz;r=000;t=lxm;y=nam;\" you can add it\n"
                + "as the following:\n"
                + "\n"
                + "Syntax: \"&=EncryptExample;\".\n"
                + "Structure: \"Beginning... middle... end\".\n"
                + "\n"
                + "\n"
                + "\"&=EncryptExample;q=rr3;w=kks;e=ppz;r=000;t=lxm;y=nam;\"\n"
                + "\"q=rr3;w=kks;e=ppz;r=000;&=EncryptExample;t=lxm;y=nam;&=EncryptExample;\"\n"
                + "\"q=rr3;w=kks;e=ppz;r=000;t=lxm;y=nam;&=EncryptExample;\"\n"
                + "\n"
                + "-Do not create of edit letters like them were a letter composed of two or more letters.\n"
                + "Example: \"ab=asn;\" or \"ImALetter=dm4;\". Doing so MAY result in program malfunction.\n"
                + "The program will not recognize \"ImALetter\" and encrypt it as \"dm4\". It has been\n"
                + "designed to state the first letter at the syntax as the \"Normal text\" or LightChar and\n"
                + "everything after THE FIRST LETTER as its encrypted equivalent.\n"
                + "\n"
                + "\n"
                + "- It is recommended to store your custom characters file in a safe place\n"
                + "out of Data Folder. It WILL be safe inside the Data Folder, but it is up\n"
                + "to you save a copy at other place. Remember, if you lose it, you won't be able\n"
                + "to unencrypt text without it.\n"
                + "\n"
                + "------------------------------------O------------------------------------\n"
                + "\n"
                + "2-SEPARATOR CHAR\n"
                + "\n"
                + "The default Separator Char of the program is = \"" + Static.defaultDarkCharSeparator + "\".\n"
                + "\n"
                + "The program needs a simbol or letter that allows it to difference a part of encrypted\n"
                + "text to another. For example, if \"a=abc;\", the Separator Char is \"" + Static.defaultDarkCharSeparator + "\" and you try to\n"
                + "encrypt \"aaa\" you will get: \"aaa" + Static.defaultDarkCharSeparator + "aaa" + Static.defaultDarkCharSeparator + "aaa" + Static.defaultDarkCharSeparator + ". \n"
                + "\n"
                + "It is prohibided to include the Separator Char inside \"Normal text\" because it will\n"
                + "make an incorrect morph of encrypted text to Normal Text. Even though, if you need to\n"
                + "include \"" + Static.defaultDarkCharSeparator + "\" in the text, you can change it inside the tab of options of the program with\n"
                + "whichever simbol, letter or even number you want; but you won't be able to write that \n"
                + "character at the encrypt  to box.\n"
                + "\n"
                + "It is recommended to keep the Separator Char as \"" + Static.defaultDarkCharSeparator + "\" because it is quite rarely used\n"
                + "in both Spanish or English languages.\n"
                + "\n"
                + "Take in consideration: \n"
                + "\n"
                + "-If you change the Separator Char, it will be remembered by the program. If you want\n"
                + "to reset it, you can do so at the options tab.\n"
                + "\n"
                + "-There is a log txt file called \"Separator Char changes\" inside the Data Folder where \n"
                + "you can find the changes the user have made to the Separator Char with date and hour.\n"
                + "\n"
                + "------------------------------------O------------------------------------\n";
    }
    
}
