
package Logic;


public class TextKeeper {
    
    public String charactersTXTdefault() {
        return "q=rr3;\n"
                + "w=kks;\n"
                + "e=ppz;\n"
                + "r=000;\n"
                + "t=lxm;\n"
                + "y=nam;\n"
                + "u=lod;\n"
                + "i=019;\n"
                + "o=mzn;\n"
                + "p=www;\n"
                + "a=xcd;\n"
                + "s=pq3;\n"
                + "d=mld;\n"
                + "f=lao;\n"
                + "h=com;\n"
                + "j=ink;\n"
                + "k=pop;\n"
                + "l=awq;\n"
                + "ñ=luk;\n"
                + "z=pen;\n"
                + "x=bty;\n"
                + "c=vag;\n"
                + "v=ope;\n"
                + "b=min;\n"
                + "n=sec;\n"
                + "m=tur;\n"
                + "g=kew;\n"
                + " = ;\n"
                + "Q=lld;\n"
                + "W=910;\n"
                + "E=plz;\n"
                + "R=999;\n"
                + "T=mnd;\n"
                + "Y=num;\n"
                + "U=dol;\n"
                + "I=091;\n"
                + "O=hjs;\n"
                + "P=ttt;\n"
                + "A=opq;\n"
                + "S=3mk;\n"
                + "D=63a;\n"
                + "F=kun;\n"
                + "H=org;\n"
                + "J=ske;\n"
                + "K=ice;\n"
                + "L=xmA;\n"
                + "Ñ=l31;\n"
                + "Z=la0;\n"
                + "X=no1;\n"
                + "C=p20;\n"
                + "V=an7;\n"
                + "B=m1n;\n"
                + "N=vq8;\n"
                + "M=lz0;\n"
                + "G=tDs;\n"
                + "á=012;\n"
                + "é=893;\n"
                + "í=kl3;\n"
                + "ó=xk4;\n"
                + "ú=sSw;\n"
                + "Á=j07;\n"
                + "É=c36;\n"
                + "Í=m34;\n"
                + "Ó=Mk0;\n"
                + "Ú=BfR;\n"
                + "0=mmW;\n"
                + "1=mnX;\n"
                + "2=XsW;\n"
                + "3=004;\n"
                + "4=maq;\n"
                + "5=mzu;\n"
                + "6=HgR;\n"
                + "7=lkE;\n"
                + "8=cXS;\n"
                + "9=eMS;\n"
                + "/=1d1;\n"
                + "$=mlW;\n"
                + ",=mQs;\n"
                + "\"=mZZ;\n"/*quote*/
                + ".=JT2;\n"/*dot*/
                + ":=92g;\n"/*dot*/
                + "#=kma;";
    }
    
}
